"""
Stage 6 — Fix & Resolve component.

This is the centrepiece of the demo. It presents the complete causal chain
in a single view so a first-time viewer immediately understands:

  ① The regression test fails on the original code   ← ❌ BEFORE FIX
  ② Incident Replay identifies the fix               ← the code change
  ③ The fix is applied
  ④ The SAME test is run again                       ← ✅ AFTER FIX
  ⑤ The test passes → incident is verified resolved

Layout (top to bottom):
  ┌─────────────────────────────────────────────────┐
  │  BEFORE FIX section header                       │
  │  ❌  Test FAILED on original code               │
  └─────────────────────────────────────────────────┘
         ↓  (arrow connector)
  ┌─────────────────────────────────────────────────┐
  │  SUGGESTED FIX section header                    │
  │  What the fix changes (description)              │
  │  Code diff                                       │
  │  ✓ APPLIED  (backend applied it)                │
  └─────────────────────────────────────────────────┘
         ↓  (arrow connector)
  ┌─────────────────────────────────────────────────┐
  │  AFTER FIX section header                        │
  │  ✅  Same test PASSED  (or ❌ FAILED)            │
  │  Test runner output (expandable)                 │
  └─────────────────────────────────────────────────┘
         ↓  (if passed)
  ╔═════════════════════════════════════════════════╗
  ║  ✅  INCIDENT RESOLVED                          ║
  ╚═════════════════════════════════════════════════╝

Data contract (all from IncidentReport — nothing invented):
  suggested_fix.description   What the fix changes
  suggested_fix.patch         Unified diff (shown if present)
  verification_result.passed  True only if backend reports PASS
  verification_result.output  Raw runner output (verbatim)
  regression_test.name        Shown in both before/after panels

PASSED / INCIDENT RESOLVED are never displayed unless
verification_result.passed is True.

Public API:
    render(report: IncidentReport) -> None
"""

from __future__ import annotations

import streamlit as st

from incident_replay.models.schemas import IncidentReport

_LABEL = (
    "font-size:0.68rem;font-weight:700;text-transform:uppercase;"
    "letter-spacing:0.07em;opacity:0.45"
)

# ── Arrow connector between panels ───────────────────────────────────────────

_ARROW = """
<div style='display:flex;flex-direction:column;align-items:center;
margin:0;padding:6px 0;opacity:0.35;user-select:none'>
  <div style='width:2px;height:16px;background:currentColor'></div>
  <div style='font-size:1rem;line-height:1;margin-top:-2px'>▼</div>
</div>
"""


def _arrow() -> None:
    st.markdown(_ARROW, unsafe_allow_html=True)


# ── Panel helper ──────────────────────────────────────────────────────────────

def _panel(bg: str, border: str, content_html: str) -> None:
    st.markdown(
        f"<div style='border:1px solid {border};"
        f"border-left:5px solid {border};"
        f"border-radius:8px;padding:16px 20px;"
        f"background:{bg}'>"
        f"{content_html}"
        f"</div>",
        unsafe_allow_html=True,
    )


# ── ① BEFORE FIX ─────────────────────────────────────────────────────────────

def _render_before(report: IncidentReport) -> None:
    rt = report.regression_test

    st.markdown(
        f"<p style='{_LABEL};margin-bottom:8px'>① Before fix</p>",
        unsafe_allow_html=True,
    )
    _panel(
        bg="rgba(220,38,38,0.04)",
        border="#dc2626",
        content_html=(
            "<div style='display:flex;align-items:center;gap:10px;margin-bottom:8px'>"
            "  <span style='font-size:1.6rem'>❌</span>"
            "  <div>"
            "    <div style='font-weight:700;font-size:1rem;color:#dc2626'>"
            "    Test FAILED on original code</div>"
            "    <div style='font-family:ui-monospace,monospace;font-size:0.78rem;"
            f"   opacity:0.6;margin-top:2px'>{rt.name}</div>"
            "  </div>"
            "</div>"
            "<div style='font-size:0.88rem;opacity:0.75;line-height:1.6'>"
            "The regression test reproduces the production incident. "
            "Running it against the original codebase confirms the defect "
            "is present and the test correctly targets the root cause."
            "</div>"
        ),
    )


# ── ② SUGGESTED FIX ──────────────────────────────────────────────────────────

def _render_fix(report: IncidentReport) -> None:
    fix = report.suggested_fix
    has_fix = bool(fix.description.strip() or fix.patch.strip())

    st.markdown(
        f"<p style='{_LABEL};margin-bottom:8px'>② Suggested fix — identified by Incident Replay</p>",
        unsafe_allow_html=True,
    )

    if not has_fix:
        st.warning("No fix was generated by the backend.", icon="⚠️")
        return

    # Description
    st.markdown(
        f"<div style='font-size:0.92rem;line-height:1.65;opacity:0.9;"
        f"margin-bottom:12px'>{fix.description}</div>",
        unsafe_allow_html=True,
    )

    # Diff
    if fix.patch:
        st.markdown(
            f"<p style='{_LABEL};margin-bottom:6px'>Code change</p>",
            unsafe_allow_html=True,
        )
        st.code(fix.patch, language="diff")

    # Apply confirmation
    st.markdown(
        "<div style='display:flex;align-items:center;gap:10px;"
        "background:rgba(5,150,105,0.06);border:1px solid rgba(5,150,105,0.2);"
        "border-radius:6px;padding:10px 14px;margin-top:8px'>"
        "  <span style='font-size:1.1rem'>🔧</span>"
        "  <div>"
        "    <div style='font-weight:600;font-size:0.88rem'>Apply Fix</div>"
        "    <div style='font-size:0.76rem;opacity:0.6;margin-top:1px'>"
        "    Applied to codebase by the backend pipeline</div>"
        "  </div>"
        "  <span style='margin-left:auto;font-size:0.8rem;font-weight:700;"
        "color:#059669'>✓ DONE</span>"
        "</div>",
        unsafe_allow_html=True,
    )


# ── ③ AFTER FIX ──────────────────────────────────────────────────────────────

def _render_after(report: IncidentReport) -> None:
    vr = report.verification_result
    rt = report.regression_test

    if vr.passed:
        st.markdown(
            f"<p style='{_LABEL};margin-bottom:8px'>③ After fix — same test, same code path</p>",
            unsafe_allow_html=True,
        )
        _panel(
            bg="rgba(5,150,105,0.05)",
            border="#059669",
            content_html=(
                "<div style='display:flex;align-items:center;gap:10px;margin-bottom:8px'>"
                "  <span style='font-size:1.6rem'>✅</span>"
                "  <div>"
                "    <div style='font-weight:700;font-size:1rem;color:#059669'>"
                "    Same test PASSED after fix</div>"
                "    <div style='font-family:ui-monospace,monospace;font-size:0.78rem;"
                f"   opacity:0.6;margin-top:2px'>{rt.name}</div>"
                "  </div>"
                "</div>"
                "<div style='font-size:0.88rem;opacity:0.75;line-height:1.6'>"
                "The identical regression test now passes. "
                "The defect is no longer present in the patched code."
                "</div>"
            ),
        )
    else:
        st.markdown(
            f"<p style='{_LABEL};margin-bottom:8px'>③ After fix — same test, same code path</p>",
            unsafe_allow_html=True,
        )
        _panel(
            bg="rgba(220,38,38,0.04)",
            border="#dc2626",
            content_html=(
                "<div style='display:flex;align-items:center;gap:10px;margin-bottom:8px'>"
                "  <span style='font-size:1.6rem'>❌</span>"
                "  <div>"
                "    <div style='font-weight:700;font-size:1rem;color:#dc2626'>"
                "    Test still FAILING after fix</div>"
                "    <div style='font-family:ui-monospace,monospace;font-size:0.78rem;"
                f"   opacity:0.6;margin-top:2px'>{rt.name}</div>"
                "  </div>"
                "</div>"
                "<div style='font-size:0.88rem;opacity:0.75;line-height:1.6'>"
                "The fix did not resolve the defect. "
                "Review the root cause analysis and suggested fix."
                "</div>"
            ),
        )

    if vr.output:
        with st.expander("Test runner output"):
            st.code(vr.output, language="")


# ── ④ VERDICT ─────────────────────────────────────────────────────────────────

def _render_verdict(report: IncidentReport) -> None:
    vr = report.verification_result

    if vr.passed:
        st.markdown(
            "<div style='border:2px solid #059669;border-radius:10px;"
            "padding:22px 26px;background:rgba(5,150,105,0.06);"
            "margin-top:8px'>"

            "<div style='display:flex;align-items:center;gap:12px;margin-bottom:10px'>"
            "  <span style='font-size:2rem'>✅</span>"
            "  <span style='font-weight:800;font-size:1.25rem;color:#059669;"
            "  letter-spacing:0.01em'>INCIDENT RESOLVED</span>"
            "</div>"

            "<div style='font-size:0.92rem;opacity:0.82;line-height:1.7'>"
            "The regression test that reproduced the production incident now passes "
            "with the fix applied. The defect has been identified, reproduced, "
            "fixed, and verified. The fix is ready to commit."
            "</div>"
            "</div>",
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            "<div style='border:2px solid #dc2626;border-radius:10px;"
            "padding:22px 26px;background:rgba(220,38,38,0.04);margin-top:8px'>"

            "<div style='display:flex;align-items:center;gap:12px;margin-bottom:10px'>"
            "  <span style='font-size:2rem'>❌</span>"
            "  <span style='font-weight:800;font-size:1.25rem;color:#dc2626'>"
            "  INCIDENT NOT RESOLVED</span>"
            "</div>"

            "<div style='font-size:0.92rem;opacity:0.82;line-height:1.7'>"
            "The regression test still fails after applying the fix. "
            "Review the root cause analysis and suggested fix."
            "</div>"
            "</div>",
            unsafe_allow_html=True,
        )


# ── Public API ────────────────────────────────────────────────────────────────

def render(report: IncidentReport) -> None:
    """Render the Fix & Resolve stage."""

    st.markdown(
        '<div class="ir-section-header">'
        '<span class="ir-section-icon">🔧</span>'
        '<span class="ir-section-title">Fix &amp; Resolve</span>'
        '</div>',
        unsafe_allow_html=True,
    )

    _render_before(report)

    _arrow()

    _render_fix(report)

    _arrow()

    _render_after(report)

    _arrow()

    _render_verdict(report)
